openapi: 3.0.0
info:
  title: Mobile Number Subscribers API
  description: ""
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Temporary host at version 1

paths:
  /subscribers:
    get:
      summary: Returns a list of subscribers.
      description: List of subscribers in the database.
      responses:
        200:
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Subscriber'
        default:
          description: Common Unexpected Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
                
  /subscribers/{id}:
    parameters:
    - name: id
      in: path
      description: "ID of subscriber to return"
      required: true
      schema:
        type: integer
        format: int64
    get:
      summary: Returns Subscriber Details
      description: "Subscriber by ID"
      responses:
        200:
          description: Subscriber Details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscriber'
        
        400:
          $ref: '#/components/responses/BadRequest'

        401:
          $ref: '#/components/responses/Unauthorized'
          
        404:
          $ref: '#/components/responses/NotFound'
        
        default:
          description: Common Unexpected Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      summary: Returns Subscriber Details
      description: "Subscriber by ID"
      responses:
        204:
          description: Subscriber Deleted Correctly
        
        400:
          $ref: '#/components/responses/BadRequest'

        401:
          $ref: '#/components/responses/Unauthorized'
          
        404:
          $ref: '#/components/responses/NotFound'
        
        default:
          description: Common Unexpected Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    patch:
      summary: Patch Subscriber Details
      description: "Patch Subscriber details by its ID"
      responses:
        200:
          description: Subscriber Details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscriber'
        
        400:
          $ref: '#/components/responses/BadRequest'

        401:
          $ref: '#/components/responses/Unauthorized'
          
        404:
          $ref: '#/components/responses/NotFound'
        
        default:
          description: Common Unexpected Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

components:
  schemas:
    Subscriber:
      type: object
      properties:
        id:
          type: integer
          format: int64
        mobileNumber:
          type: string
          pattern: '^[1-9]\d{1,14}$'
          example: "35699123456"
        userId:
          type: integer
          format: int64
        ownerId:
          type: integer
          format: int64
        subscribtionDate:
          type: string
          format: date-time
          
    ErrorMessage:
      type: object
      properties:
        timestamp: 
          type: string
        status:
          type: integer
        error: 
          type: string
        message: 
          type: string
        path: 
          type: string

  responses:
    Unauthorized:
      description: Unauthorised Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
            
    NotFound:
      description: Resource Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
            
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
            
    UnexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        