server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: /api
  

db:
  host: localhost
  port: 3306
  name: vdf-mobile-numbers


spring:
  application:
    name: mobile-numbers
    

  
