server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: /api/v1
  

db:
  host: localhost
  port: 3306
  name: vdf-mobile-numbers


spring:
  application:
    name: mobile-numbers
        
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      
    
  datasource:
    username: root
    password: root159*
    jdbcUrl: jdbc:mysql://localhost:3306/vdf-mobile-numbers?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: spring-user-test
      password: u53r*T3st
